### ISSUE TITLE
Can I Fetch data from classic OPC Server?

### ISSUE THREAD

**Issue by tejasklodha** [parallelbgls/Modbus.Net#5]
Dear Sir,

I want to fetch data from classic OPC DA Server.
Can it possible by usingModbus.Net?

Thanks,

**Comment by parallelbgls** [comment]
Of-cause, Please download Modbus.Net and Modbus.Net.OPC at the same time. It included an OPC DA(Data access) implementation and an OPC UA implementation.
The English document will be published soon I finish version 1.3.8

**Comment by parallelbgls** [comment]
But remember if your OPC DA server is hosted as an administrator application, your client must be run in administrator.

**Comment by tejasklodha** [comment]
Dear Sir,

But I am unable to load your project in Visual studio 2015 .
Find screenshot

![screenshot_1](https://cloud.githubusercontent.com/assets/25738779/26238881/928f4f26-3c98-11e7-966d-1eb3fe1d3c33.png)

**Comment by parallelbgls** [comment]
Project is using Visual Studio 2017

**Comment by parallelbgls** [comment]
Please Downgrade to 1.2.X. for Visual Studio 2015 using tags.

**Comment by tejasklodha** [comment]
Dear Sir,

Now I load your project in VS17 and able to run your project
Now I want to change server name and use my OPC Da server and show live value of that variables.
Can you guide that What changes needed ?
Can you provide documentation ?

Thanks

**Comment by parallelbgls** [comment]
Alright, I have to apologize that  I have to make this project stabilize because of a huge project that need to read over 16,000 points. And I need to fix the unit test after this project. So English document would be accomplished not so soon.
Opc is a little bit different from other protocols. So I have a quick way for you to understand that. Cause there is a sample da machine FBox/FBoxOpcDaMachine in Modbus.Net.OPC, and OpcTest in tests for calling. This is the quickest way for you to learn how to read OPC DA data.
For Opc link address, you can download a free software called "Matrikon OPC Explorer" to get the server address.

**Comment by tejasklodha** [comment]
Dear Sir,

Thanks for Info... At the End I am also one developer so I understand that it's not easy to work both Code and documentation at same time......

I just want to read data from OPC DA server in WPF application.... 
Let Me know when English Document Available on Web Site?.

Thanks,

**Comment by parallelbgls** [comment]
Sorry, my message is late. I sucked in some projects last week and I think 1.3.X version may stable now.
I will update wiki document from tomorrow, both in Chinese and English.

**Comment by parallelbgls** [comment]
1.3.9 Doc Update Complete. Please feedback if you have problems in doc.
